#!/bin/bash

# 定義要替換的文件
FILE="index.html"

# 獲取當前 Unix 時間戳
CURRENT_TIME=$(date +%s)

# 檢查文件是否存在
if [ -f "$FILE" ]; then
  # 使用 sed 來替換文件中的時間戳
  # 假設時間戳的格式是數字
  sed -i "s/\?dummy=[0-9]\{10\}/?dummy=$CURRENT_TIME/g" "$FILE"
fi

# 添加修改後的文件到暫存區
git add "$FILE"
